language: ruby
rvm:
  - 2.3.0
  - 2.2.3
  - 2.1.1
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode

matrix:
  allow_failures:
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: rbx
    - rvm: 1.9.3


services:
  - couchdb

script: bundle exec rspec -fd spec/leanback_spec.rb
