version: '3'
services:
  couchdb:
    image: "apache/couchdb:1.7.1"
    expose:
      - "5984"
    ports:
      - 5984:5984

  leanback:
    build: .
    links:
      - couchdb:couchdb
    volumes:
      - .:/usr/src/leanback
    environment:
      COUCHDB_ADDRESS: couchdb
    tty: true
    stdin_open: true
    entrypoint: bundle exec rake repl
